# Site settings
author: Will Lee
title: A Cup of Coffee and Some Code
header-img: img/home-bg.png
email: will.ik.lee@gmail.com
copyright_name: Will Lee
description: > # this means to ignore newlines until "baseurl:"
  Musings of my journey into the world of coding!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  freeWillee

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
