# Site settings
author: Will L
title: theWiredCoder
header-img: img/home-bg.png
email: will.ik.lee@gmail.com
copyright_name: Will L
description: > # this means to ignore newlines until "baseurl:"
  Musings of my journey into the world of coding!
url: "https://thewiredcoder.com"
twitter_username: 
github_username:  freeWillee

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
